[build]
builder = "NIXPACKS"
watchPatterns = ["**/*.vue", "**/*.js", "**/*.ts", "**/*.json", "**/*.md"]

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NODE_VERSION = "20.19.0"
